### ISSUE TITLE
Dashboard notifications

### ISSUE THREAD

**Issue by xDae** [zach-adams/hgv-deploy-full#11]
Anybody know why in a fresh instalation of wordpress I have always the dashboard notifications?

![Image of Yaktocat](http://i.imgur.com/eKbB5lB.png)

If I accept the messages and reload the dashboard it appears again (maybe some cookie its not working)

**Comment by ahansson89** [comment]
Does wp-admin/admin-ajax.php work?

**Comment by ahansson89** [comment]
https://github.com/zach-adams/hgv-deploy-full/issues/10

**Comment by xDae** [comment]
Setting define('DB_HOST', '127.0.0.1'); (or the digital ocean droplet ip) didnt work, the popups follows me everywhere :sob:

**Comment by xDae** [comment]
I have detected the problem, solved stopping hhvm `sudo service hhvm stop`
