### ISSUE TITLE
No package matching 'hhvm' is available

### ISSUE THREAD

**Issue by Kosteg** [zach-adams/hgv-deploy-full#20]
root@vm2321:~/hgv-deploy-full# sudo ansible-playbook -i hosts playbook.yml -c local

PLAY [all] *******************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [vstogesena.ru]

TASK: [common | Install necessary packages for proper system state] **********\* 
changed: [vstogesena.ru] => (item=sysv-rc-conf,python-apt,python-pycurl,python-mysqldb,git,curl,unzip,php5-mysql,traceroute,ack-grep,subversion,autojump,siege)

TASK: [common | Get Composer] ************************************************\* 
changed: [vstogesena.ru]

TASK: [common | Install PsySH] ***********************************************\* 
changed: [vstogesena.ru]

TASK: [common | Install Boris] ***********************************************\* 
changed: [vstogesena.ru]

TASK: [common | Fix the stdin bug, step 1] ***********************************\* 
changed: [vstogesena.ru]

TASK: [common | Fix the stdin bug, step 2] ***********************************\* 
changed: [vstogesena.ru]

TASK: [common | Create swap file] ********************************************\* 
changed: [vstogesena.ru]

TASK: [common | Setup swap area] *********************************************\* 
changed: [vstogesena.ru]

TASK: [common | Change swap file permissions] ********************************\* 
changed: [vstogesena.ru]

TASK: [common | Write swap entry in fstab] ***********************************\* 
changed: [vstogesena.ru]

TASK: [common | Swap on] *****************************************************\* 
changed: [vstogesena.ru]

TASK: [hhvm | Enable HHVM repo key] ******************************************\* 
changed: [vstogesena.ru]

TASK: [hhvm | Enable HHVM repo] **********************************************\* 
changed: [vstogesena.ru]

TASK: [hhvm | Install HHVM] **************************************************\* 
failed: [vstogesena.ru] => {"failed": true}
msg: No package matching 'hhvm' is available

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/playbook.retry

vstogesena.ru              : ok=14   changed=13   unreachable=0    failed=1

**Comment by ghost** [comment]
I got this error too and i have no idea what to do.

**Comment by zach-adams** [comment]
Sorry for the delay,

Can I see the value of your 'sources.list' file in '/etc/apt/?

**Comment by ghost** [comment]
http://pastebin.com/c885uqts

**Comment by zach-adams** [comment]
It looks like for some reason the HHVM repository isn't being added via Apt, you can add it manually by running this command:

```
sudo add-apt-repository 'deb http://dl.hhvm.com/ubuntu trusty main'
```

After that run

```
sudo apt-get update
```

Then try running the playbook again!

**Comment by ghost** [comment]
After i ran the commands you said, i checked and there was no change in sources.list and i got the same error again.

**Comment by zach-adams** [comment]
Try installing hhvm outright with:

```
sudo apt-get install hhvm
```

**Comment by ghost** [comment]
root@oyunakilli:~# sudo apt-get install hhvm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package hhvm

no luck.

**Comment by zach-adams** [comment]
Hmm, what did the "add-apt-repository" command output when you tried it?

**Comment by ghost** [comment]
nothing

**Comment by zach-adams** [comment]
As in it didn't return a "command not found" or anything at all?

You can add the following manually at the end of your 'sources.list' file if add-apt-repository isn't working

```
deb http://dl.hhvm.com/ubuntu trusty main
```

**Comment by ghost** [comment]
added it manually and run apt-get update, got this error at the end;

W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

and still the same error at the installing.

**Comment by zach-adams** [comment]
Very weird, what kind of server are you trying this on?

**Comment by ghost** [comment]
2GB Ram 40GB SSD Disk Ubuntu 14.04 x32 Digitalocean

**Comment by zach-adams** [comment]
Hi @wiuxo,

Looks like HHVM [doesn't support 32 bit OS's](https://github.com/facebook/hhvm/wiki/FAQ). You can switch to the 64 bit Ubuntu in Digital Ocean or you can remove the following line in the "playbook.yml":

```
    - { role: hhvm, when: ansible_lsb.major_release | int >= 14 }
```

And rerun the playbook. Then you can follow [these instructions](https://github.com/zach-adams/hgv-deploy-full#switching-hhvm-back-to-php-fpm) to only use PHP-FPM rather than HHVM

**Comment by ghost** [comment]
Which one do you suggest?

**Comment by zach-adams** [comment]
I would recommend switching to 64 bit Ubuntu unless you have any reasons to stay with 32 bit

**Comment by ghost** [comment]
Thanks for everything. Switched to 64bit and everything worked perfect.
