### ISSUE TITLE
Swap

### ISSUE THREAD

**Issue by juanbrujo** [zach-adams/hgv-deploy-full#22]
It is recommendable enable swap to VPS with 1GB RAM?

**Comment by zach-adams** [comment]
Hi juan, 

You can read more about swap space [here](https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s1-swap-what-is.html), basically swap space will cover you if your RAM is full, though it's not nearly as performant. I recommend enabling it as a "just in case" fallback.
