### ISSUE TITLE
Pagespeed Mod

### ISSUE THREAD

**Issue by iskandarsulaili** [zach-adams/hgv-deploy-full#31]
In anyway, how can I add pagespeed & redis work together with nginx in this script? Will it help overall performance?

**Comment by yobasystems** [comment]
Nginx has to be built from source. The best place to look is on scotthelme.co.uk, he gives full info on building from source retaining all the list of installed packages.

**Comment by cAstraea** [comment]
Think it might be tricky running varnish and pagespeed and configuring Downstream Caches

**Comment by iskandarsulaili** [comment]
Yes indeed. So far I tried but still no luck.

This email has been sent from a virus-free computer protected by Avast.
www.avast.com https://www.avast.com/sig-email
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by therealssj** [comment]
I did succeed in this but the results I got after running pagespeed were way worse than without it!
The only place I saw improvement was my pagespeed score other than that the speed of my site actually decreased.

**Comment by iskandarsulaili** [comment]
I see.. Thanks! I guess we need to skip this and prepare for latest version
ubuntu.

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
