### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by iskandarsulaili** [zach-adams/hgv-deploy-full#50]
I tried to setup Let's Encrypt (with various method) but fail. Same method I am using for other server (not hgv) it's work find. Let's Encrypt failed challenge test although the folder are accessible.

**Comment by kleinaber** [comment]
Hi @cakobox did the same thing yesterday and ran into similar issues, but was able to resolve as follows:

`sudo nano /etc/nginx/sites-available/example.com`

find this line and remove or disable it:

`#location ~ /\. { deny  all; access_log off; log_not_found off; }`

Please be sure to switch it back on after Let's Encrypt is done.

**Comment by cakobox** [comment]
Thanks. It's help!

**Comment by iskandarsulaili** [comment]
Thanks. It's help!
