### ISSUE TITLE
Ansible not updating

### ISSUE THREAD

**Issue by ruudvh** [zach-adams/hgv-deploy-full#6]
The issue I am having is that Ansible is not properly updated when installing, and because only 1.7 supports `run_once` the user will receive the following error:
`ERROR: run_once is not a legal parameter in an Ansible task or handler`

To fix this issue I am running the [following](http://docs.ansible.com/intro_installation.html#latest-releases-via-apt-ubuntu) commands to install the latest version of Ansible:

```
$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update
$ sudo apt-get install ansible
```

These commands will thus replace step 2, 3, and (partially) 4 on the Readme.MD.

Note: `sotware-properties-common` is the same as `python-software-properties` but for newer ubuntu distributions and is required to run `apt-add-repository`.

Off-topic: Not trying to fill your inbox with issues, but I am currently writing a Wordpress Deployment guide and one of the options is to use EasyEngine or your HGV - so you might hear from me so now and then ;).

**Comment by zach-adams** [comment]
Good catch! I'll add `sudo apt-get install software-properties-common` and perhaps change around the Apt update procedure.

Also no problem about the questions! Always open at zach@zach-adams.com or the issues page!
