### ISSUE TITLE
Varnish and logged in on frontend

### ISSUE THREAD

**Issue by ahansson89** [zach-adams/hgv-deploy-full#9]
I have a problem where I cannot be logged in on frontend. I narrowed it down to be a problem with Varnish as when I turn Varnish off I can be logged in on frontend.

**Comment by zach-adams** [comment]
@ahansson89 Sorry for the delay in response! Yes that is a downside of Varnish in that it can't tell when you're browsing the front end as a logged in user or not, however it should work correctly on any of the backend pages. 

The only solution (at least right now) is turning off Varnish and just running Nginx normally.
